{% set name = "pkce" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pkce-{{ version }}.tar.gz
  sha256: 9775fd76d8a743d39b87df38af1cd04a58c9b5a5242d5a6350ef343d06814ab6

build:
  skip: true  # [py<3.0]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0

test:
  imports:
    - pkce
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RomeoDespres/pkce
  summary: PKCE Python generator.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - mattkram
